=== TheGiddyLimit/homebrew/_schema/homebrew.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"version": "1.7.1",
	"type": "object",
	"description": "Homebrew for 5etools. Should include arrays titled similarly to the main site data, e.g. `spell` or `class`",
	"properties": {
		"_meta": {
			"description": "Metadata for the included data arrays",
			"type": "object",
			"properties": {
				"sources": {
					"type": "array",
					"items": {
						"type": "object",
						"description": "A set of properties describing a \"source.\" A source could be, for example, a homebrew PDF, book, or blog post.",
						"properties": {
							"json": {
								"type": "string",
								"description": "An identifying string, as seen in the JSON in \"source\" fields."
							},
							"abbreviation": {
								"type": "string",
								"description": "Abbreviated form of the source, to display on the site."
							},
							"color": {
								"type": "string",
								"description": "HTML hex color code this source should use when displayed in lists, e.g. 'ff00ff'",
								"pattern": "^([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$"
							},
							"full": {
								"type": "string",
								"description": "Full title of the source, to display on the site."
							},
							"authors": {
								"type": "array",
								"description": "A list of authors who created the homebrew source.",
								"items": {
									"type": "string",
									"description": "Author name."
								}
							},
							"convertedBy": {
								"type": "array",
								"description": "An optional list of people who contributed to converting the source to 5etools format.",
								"items": {
									"type": "string",
									"description": "Contributor name."
								}
							},
							"dateReleased": {
								"type": "string",
								"format": "date",
								"description": "The date of release of the source, in the format YYYY-MM-DD (RFC3339)."
							},
							"version": {
								"type": "string",
								"description": "The source version, e.g. \"1.2.3\"."
							},
							"url": {
								"type": "string",
								"description": "A direct link to the source, if available in web form or on a store."
							},
							"targetSchema": {
								"type": "string",
								"description": "The target schema version in 5etools, e.g. \"1.2.3\"."
							}
						},
						"required": [
							"json",
							"abbreviation",
							"full",
							"version"
						],
						"additionalProperties": false
					}
				},
				"skills": {
					"type": "object",
					"description": "Object keys are Skill names, which can referenced using {@skill <key>} (case sensitive)",
					"patternProperties": {
						".*": {
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					}
				},
				"senses": {
					"type": "object",
					"description": "Object keys are Sense names, which can referenced using {@sense <key>} (case insensitive)",
					"patternProperties": {
						".*": {
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					}
				},
				"spellSchools": {
					"type": "object",
					"description": "Object names are spell school abbreviations (e.g. `\"X\"`); values should be objects with `\"full\"`` (used in the main entry, e.g. \"Evocation\") and `\"short\"` (used in the list view, e.g. `\"Evoc.\"`) key/values.",
					"patternProperties": {
						".*": {
							"type": "object",
							"properties": {
								"full": {
									"type": "string"
								},
								"short": {
									"type": "string"
								},
								"color": {
									"type": "string",
									"description": "HTML hex color code this source should use when displayed in lists, e.g. 'ff00ff'",
									"pattern": "^([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$"
								}
							},
							"required": [
								"full",
								"short"
							]
						}
					}
				},
				"spellDistanceUnits": {
					"type": "object",
					"description": "Object names are spell distance units (e.g. `\"hectares\"`); values should be objects with optional `\"singular\"`` (singular form of the unit, e.g. \"foot\" for the singular of \"feet\"--if unspecified, a trailing \"s\" is removed from the plural version, if it exists, and the result is used as the singular form) and `\"feetPerUnit\"` (e.g. for a \"yards\" custom unit, this would be `3`, as there are three feet in a yard) key/values.",
					"patternProperties": {
						".*": {
							"type": "object",
							"properties": {
								"feetPerUnit": {
									"type": "number"
								},
								"singular": {
									"type": "string"
								}
							},
							"required": [
								"feetPerUnit"
							]
						}
					}
				},
				"optionalFeatureTypes": {
					"type": "object",
					"description": "Object names are optional feature \"type\" shorthands (e.g. \"EI\" for \"Eldritch Invocation\" which will be displayed in the list view as a sortable column",
					"patternProperties": {
						".*": {
							"type": "string"
						}
					}
				},
				"psionicTypes": {
					"type": "object",
					"description": "Object names are psionic type abbreviations (e.g. `\"X\"`); values should be objects with `\"full\"`` (used in the main entry, e.g. \"Greater Discipline\") and `\"short\"` (used in the list view, e.g. `\"G. Discipline\"`) key/values.",
					"patternProperties": {
						".*": {
							"type": "object",
							"properties": {
								"full": {
									"type": "string"
								},
								"short": {
									"type": "string"
								},
								"hasOrder": {
									"description": "If this type has a psionic order.",
									"type": "boolean"
								},
								"isAltDisplay": {
									"description": "If this type should display its psionic type/order with the format \"Greater Discipline (Awakened)\" instead of the standard \"Awakened Greater Discipline\"",
									"type": "boolean"
								}
							},
							"required": [
								"full",
								"short"
							]
						}
					}
				},
				"dateAdded": {
					"type": "integer",
					"description": "The epoch timestamp (in seconds) when the homebrew was added to the repository. Not guaranteed to be anywhere near accurate."
				},
				"dateLastModified": {
					"type": "integer",
					"description": "The epoch timestamp (in seconds) when the homebrew was last modified. Not guaranteed to be anywhere near accurate."
				},
				"currencyConversions": {
					"type": "object",
					"description": "Keys should be uniquely-named value conversion objects, and can be referenced from item entities as \"currencyConversion\": \"<MyKey>\". The currency conversion info will then be used when rendering the value of the item.",
					"patternProperties": {
						".*": {
							"type": "array",
							"items": {
								"type": "object",
								"properties": {
									"coin": {
										"type": "string",
										"description": "Coin abbreviation, e.g. \"gp\""
									},
									"mult": {
										"type": "number",
										"description": "A multiplier for converting copper to this currency, e.g. \"0.01\" for standard gold pieces"
									},
									"isFallback": {
										"type": "boolean",
										"description": "If true, this currency will be used as a fallback when the copper value of the item is a fractional value (e.g. a single ball bearing is worth 0.1 cp; marking gold as the fallback currency would have this be converted to gold)."
									}
								},
								"required": [
									"coin",
									"mult"
								]
							}
						}
					}
				},
				"dependencies": {
					"description": "A map of `\"<data property>\": [\"<JsonSource1>\", ..., \"<JsonSourceN>\"]`. Entities from these sources can then be extended/referenced in this file.",
					"type": "object",
					"patternProperties": {
						"^[a-zA-Z]+$": {
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					}
				},
				"includes": {
					"description": "Structure as per \"dependencies\". Additional sources to be included when loading the file.",
					"type": "object",
					"patternProperties": {
						"^[a-zA-Z]+$": {
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					}
				},
				"internalCopies": {
					"description": "An array of keys that are copied from within the current document. e.g. \"item\", \"monsterFluff\", \"background\" etc.",
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"unlisted": {
					"description": "If this homebrew file should be ignored/hidden by any indexer.",
					"type": "boolean"
				}
			},
			"required": [
				"sources"
			],
			"additionalProperties": false
		},
		"makebrewCreatureTrait": {
			"description": "Additional trait templates which can be used in the homebrew builder.",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"source": {
						"type": "string"
					},
					"entries": {
						"type": "array"
					}
				},
				"required": [
					"name",
					"source",
					"entries"
				]
			}
		},
		"adventure": {
			"$ref": "adventures.json#/properties/adventure"
		},
		"book": {
			"$ref": "books.json#/properties/book"
		},
		"class": {
			"$ref": "class/class.json#/properties/class"
		},
		"subclass": {
			"$ref": "class/class.json#/properties/subclass"
		},
		"subclassFeature": {
			"$ref": "class/class.json#/properties/subclassFeature"
		},
		"spell": {
			"$ref": "spells/spells.json#/properties/spell"
		},
		"roll20Spell": {
			"description": "Based on the Roll20 JSON data, example available here: https://app.roll20.net/compendium/dnd5e/Spells:Fireball.json",
			"$ref": "spells/roll20.json#/properties/spell"
		},
		"foundrySpell": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"description": "Used to link spells in the homebrew to this extra Foundry data",
						"type": "string"
					},
					"source": {
						"description": "Used to link spells in the homebrew to this extra Foundry data",
						"type": "string"
					},
					"data": {
						"type": "object",
						"description": "Foundry data",
						"properties": {
							"target.value": {
								"type": "integer"
							},
							"target.units": {
								"type": "string"
							},
							"target.type": {
								"description": "From Foundry's `CONFIG.DND5E.targetTypes`",
								"type": "string",
								"enum": [
									"ally",
									"creature",
									"cylinder",
									"cone",
									"cube",
									"enemy",
									"line",
									"none",
									"object",
									"radius",
									"self",
									"space",
									"sphere",
									"square",
									"wall"
								]
							}
						}
					}
				},
				"required": [
					"name",
					"source"
				],
				"additionalProperties": false
			}
		},
		"item": {
			"$ref": "items.json#/properties/item"
		},
		"itemGroup": {
			"$ref": "items.json#/properties/itemGroup"
		},
		"baseitem": {
			"$ref": "items-base.json#/properties/baseitem"
		},
		"itemProperty": {
			"$ref": "items-base.json#/properties/itemProperty"
		},
		"itemType": {
			"$ref": "items-base.json#/properties/itemType"
		},
		"variant": {
			"$ref": "magicvariants.json#/properties/variant"
		},
		"background": {
			"$ref": "backgrounds.json#/properties/background"
		},
		"backgroundFluff": {
			"$ref": "fluff-backgrounds.json#/properties/backgroundFluff"
		},
		"condition": {
			"$ref": "conditionsdiseases.json#/properties/condition"
		},
		"disease": {
			"$ref": "conditionsdiseases.json#/properties/disease"
		},
		"status": {
			"$ref": "conditionsdiseases.json#/properties/status"
		},
		"deity": {
			"$ref": "deities.json#/properties/deity"
		},
		"encounter": {
			"$ref": "encounters.json#/properties/encounter"
		},
		"feat": {
			"$ref": "feats.json#/properties/feat"
		},
		"object": {
			"$ref": "objects.json#/properties/object"
		},
		"psionic": {
			"$ref": "psionics.json#/properties/psionic"
		},
		"race": {
			"$ref": "races.json#/properties/race"
		},
		"subrace": {
			"$ref": "races.json#/properties/subrace"
		},
		"raceFluff": {
			"$ref": "fluff-races.json#/properties/raceFluff"
		},
		"reward": {
			"$ref": "rewards.json#/properties/reward"
		},
		"ship": {
			"$ref": "vehicles.json#/properties/vehicle"
		},
		"table": {
			"$ref": "tables.json#/properties/table"
		},
		"trap": {
			"$ref": "trapshazards.json#/properties/trap"
		},
		"hazard": {
			"$ref": "trapshazards.json#/properties/hazard"
		},
		"optionalfeature": {
			"$ref": "optionalfeatures.json#/properties/optionalfeature"
		},
		"variantrule": {
			"$ref": "variantrules.json#/properties/variantrule"
		},
		"legendaryGroup": {
			"$ref": "bestiary/legendarygroups.json#/properties/legendaryGroup"
		},
		"language": {
			"$ref": "languages.json#/properties/language"
		},
		"monster": {
			"$ref": "bestiary/bestiary.json#/properties/monster"
		},
		"itemFluff": {
			"$ref": "fluff-items.json#/properties/itemFluff"
		},
		"monsterFluff": {
			"$ref": "bestiary/fluff-bestiary.json#/properties/monsterFluff"
		},
		"bookData": {
			"$ref": "book/book.json#/properties/data"
		},
		"adventureData": {
			"$ref": "adventure/adventure.json#/properties/data"
		},
		"$schema": {
			"description": "An optional key that allows you specify the schema you want to verify against.\nIt is strongly advised that you leave this key out when submitting to the repo.\nTo reduce work it is advised that you set up your environment to use the same schema for all homebrew files.",
			"type": "string"
		},
		"vehicle": {
			"$ref": "vehicles.json#/properties/vehicle"
		},
		"vehicleUpgrade": {
			"$ref": "vehicles.json#/properties/vehicleUpgrade"
		},
		"action": {
			"$ref": "actions.json#/properties/action"
		},
		"recipe": {
			"$ref": "recipes.json#/properties/recipe"
		},
		"classFeature": {
			"$ref": "class/class.json#/properties/classFeature"
		},
		"cult": {
			"$ref": "cultsboons.json#/properties/cult"
		},
		"boon": {
			"$ref": "cultsboons.json#/properties/boon"
		},
		"charoption": {
			"$ref": "charcreationoptions.json#/properties/charoption"
		},
		"name": {
			"$ref": "names.json#/properties/name"
		},
		"foundryClassFeature": {
			"$ref": "class/foundry.json#/properties/classFeature"
		},
		"foundrySubclassFeature": {
			"$ref": "class/foundry.json#/properties/subclassFeature"
		}
	},
	"additionalProperties": false
}

=== TheGiddyLimit/homebrew/item/p4535992; Stonemoon Shop.json
{
	"_meta": {
		"sources": [
			{
				"json": "StonemoonShop",
				"abbreviation": "StonemoonShop",
				"full": "Stonemoon Shop (collection of my favorite items)",
				"authors": [
					"The community (Roll20,Reddit,Pinterest,...)"
				],
				"convertedBy": [
					"p4535992"
				],
				"version": "1.3.1",
				"url": "",
				"targetSchema": "1.0.0"
			}
		],
		"currencyConversions": {
			"goblincurrency": [
				{
					"coin": "ap",
					"mult": 1
				},
				{
					"coin": "bp",
					"mult": 0.5,
					"isFallback": true
				}
			]
		},
		"dateAdded": 1537874753,
		"dateLastModified": 1537874753
	},
	"itemProperty": [
		{
			"abbreviation": "Spiked",
			"source": "StonemoonShop",
			"entries": [
				{
					"type": "entries",
					"name": "Spiked",
					"entries": [
						"When hit by a weapon with the spiked property the target gains {@dice +1} damage."
					]
				}
			]
		}
	],
	"item": [
		{
			"name": "Spider Staff",
			"baseItem": "staff|PHB",
			"weaponCategory": "martial",
			"weight": 6,
			"dmg1": "1d6",
			"dmg2": "1d6 poison damage",
			"dmgType": "B",
			"property": [
				"H",
				"R",
				"2H"
			],
			"armor": false,
			"ac": "0",
			"stealth": false,
			"rarity": "uncommon",
			"wondrous": false,
			"value": 1000,
			"weapon": true,
			"staff": true,
			"recharge": "dusk",
			"charges": 10,
			"source": "StonemoonShop",
			"entries": [
				"The top of this black, adamantine staff is shaped like a spider. The staff weighs 6 pounds. You must be attuned to the staff to gain its benefits and cast its spells.",
				"The staff can be wielded as a quarterstaff. It deals {@dice 1d6} extra poison damage on a hit when used to make a weapon attack.",
				"The staff has 10 charges, which are used to fuel the spells within it. With the staff in hand, you can use your action to cast one of the following spells from the staff if the spell is on your class's spell list: {@spell spider climb} (1 charge) or {@spell web} (2 charges, spell save DC 15). No components are required.",
				"The staff regains {@dice 1d6 + 4} expended charges each day at dusk. If you expend the staff's last charge, roll a {@dice d20}. On a 1, the staff crumbles to dust and is destroyed."
			],
			"attachedSpells": [
				"spider climb",
				"web"
			],
			"fluff": {
				"images": [
					{
						"type": "image",
						"href": {
							"type": "external",
							"url": "https://i.imgur.com/jrmsk3k.jpg"
						}
					}
				],
				"entries": []
			}
		},
		{
			"name": "Staff of Defense",
			"baseItem": "staff|PHB",
			"weaponCategory": "martial",
			"weight": 3,
			"dmg1": "1d6",
			"dmgType": "B",
			"property": [
				"H",
				"R",
				"2H"
			],
			"armor": false,
			"ac": "0",
			"stealth": false,
			"rarity": "uncommon",
			"wondrous": false,
			"value": 1000,
			"weapon": true,
			"staff": true,
			"recharge": "dawn",
			"charges": 10,
			"source": "StonemoonShop",
			"entries": [
				"This slender, hollow staff is made of glass yet is as strong as oak. It weighs 3 pounds. You must be attuned to the staff to gain its benefits and cast its spells.",
				"While holding the staff, you have a +1 bonus to your Armor Class.",
				"The staff has 10 charges, which are used to fuel the spells within it. With the staff in hand, you can use your action to cast one of the following spells from the staff if the spell is on your class's spell list: {@spell mage armor} (1 charge) or {@spell shield} (2 charges). No components are required.",
				"The staff regains {@dice 1d6 + 4} expended charges each day at dawn. If you expend the staff's last charge, roll a {@dice d20}. On a 1, the staff shatters and is destroyed."
			],
			"bonusAc": "+1",
			"attachedSpells": [
				"mage armor",
				"shield"
			],
			"fluff": {
				"images": [
					{
						"type": "image",
						"href": {
							"type": "external",
							"url": "https://i.imgur.com/G0w2N7F.jpg"
						}
					}
				],
				"entries": []
			}
		},
		{
			"name": "Wand of Magic Missiles",
			"baseItem": "wand|PHB",
			"type": "WD",
			"weaponCategory": "martial",
			"weight": 3,
			"dmg1": "1d6",
			"dmgType": "B",
			"property": [
				"H",
				"R",
				"2H"
			],
			"armor": false,
			"ac": "0",
			"stealth": false,
			"rarity": "uncommon",
			"wondrous": false,
			"value": 1000,
			"weapon": true,
			"wand": true,
			"recharge": "dawn",
			"charges": 7,
			"source": "StonemoonShop",
			"entries": [
				"This wand has 7 charges. With the wand in hand, you can use your action to fire the {@spell magic missile} spell from the wand\u2014no components required\u2014and expend 1 to 3 of the wand's charges. For each charge you expend beyond 1, the spell's level increases by 1. You can use this wand even if you are incapable of casting spells.",
				"The wand regains {@dice 1d6 + 1} expended charges each day at dawn. If you expend the wand's last charge, roll a {@dice d20}. On a 1, the wand crumbles into ash and is destroyed."
			],
			"attachedSpells": [
				"magic missile"
			],
			"fluff": {
				"images": [
					{
						"type": "image",
						"href": {
							"type": "external",
							"url": "https://i.imgur.com/BO612vr.jpg"
						}
					}
				],
				"entries": []
			}
		},
		{
			"name": "Spell Scroll",
			"type": "SC",
			"baseItem": "scroll|PHB",
			"weaponCategory": "",
			"weight": 0,
			"armor": false,
			"ac": "0",
			"stealth": false,
			"rarity": "varies",
			"wondrous": false,
			"value": 1000,
			"weapon": false,
			"source": "StonemoonShop",
			"entries": [
				"A spell scroll bears the words of a single spell, written in a mystical cipher. If the spell is on your class's spell list, you can use an action to read the scroll and cast its spell without having to provide any of the spell's components. Otherwise, the scroll is unintelligible.",
				"If the spell is on your class's spell list but of a higher level than you can normally cast, you must make an ability check using your spellcasting ability to determine whether you cast it successfully. The DC equals 10 + the spell's level. On a failed check, the spell disappears from the scroll with no other effect.",
				"Once the spell is cast, the words on the scroll fade, and the scroll itself crumbles to dust."
			],
			"fluff": {
				"images": [
					{
						"type": "image",
						"href": {
							"type": "external",
							"url": "https://i.imgur.com/DEWU6Me.png"
						}
					}
				],
				"entries": []
			}
		},
		{
			"name": "Ring of Protection",
			"baseItem": "ring|PHB",
			"type": "RG",
			"weaponCategory": "varies",
			"weight": 0,
			"armor": false,
			"ac": "0",
			"stealth": false,
			"rarity": "rare",
			"wondrous": false,
			"reqAttune": true,
			"value": 1000,
			"weapon": false,
			"source": "StonemoonShop",
			"entries": [
				"While you are wearing this ring and are attuned to it, you have a +1 bonus to your Armor Class and saving throws."
			],
			"bonusAc": "+1",
			"bonusSavingThrow": "+1",
			"fluff": {
				"images": [
					{
						"type": "image",
						"href": {
							"type": "external",
							"url": "https://i.imgur.com/29d5Z4Z.jpg"
						}
					}
				],
				"entries": []
			}
		},
		{
			"name": "Boots of Striding and Springing",
			"weaponCategory": "varies",
			"weight": 0,
			"armor": false,
			"ac": "0",
			"stealth": false,
			"rarity": "uncommon",
			"wondrous": true,
			"reqAttune": true,
			"value": 1000,
			"weapon": false,
			"source": "StonemoonShop",
			"entries": [
				"Your speed while you wear these boots becomes 30 feet, unless your walking speed is higher, and your speed is not reduced if you are encumbered or wearing heavy armor. In addition, whenever you jump, you can jump three times the normal distance."
			],
			"fluff": {
				"images": [
					{
						"type": "image",
						"href": {
							"type": "external",
							"url": "https://i.imgur.com/QT2Ubk1.jpg"
						}
					}
				],
				"entries": []
			}
		},
		{
			"name": "Gauntlets of Ogre Power",
			"weaponCategory": "varies",
			"weight": 0,
			"armor": false,
			"ac": "0",
			"stealth": false,
			"rarity": "uncommon",
			"wondrous": true,
			"reqAttune": true,
			"value": 1000,
			"weapon": false,
			"source": "StonemoonShop",
			"entries": [
				"While you wear these gauntlets, your Strength becomes 19. If your Strength is already 19 or higher, the gauntlets have no effect on you."
			],
			"fluff": {
				"images": [
					{
						"type": "image",
						"href": {
							"type": "external",
							"url": "https://i.imgur.com/AgSIiu9.jpg"
						}
					}
				],
				"entries": []
			}
		},
		{
			"name": "Amulet of Proof Against Detection and Location",
			"weaponCategory": "varies",
			"weight": 0,
			"armor": false,
			"ac": "0",
			"stealth": false,
			"rarity": "uncommon",
			"wondrous": true,
			"reqAttune": true,
			"value": 1000,
			"weapon": false,
			"source": "StonemoonShop",
			"entries": [
				"While wearing this amulet, you are hidden from divination magic. You can't be targeted by such magic or perceived through magical scrying sensors."
			],
			"fluff": {
				"images": [
					{
						"type": "image",
						"href": {
							"type": "external",
							"url": "https://i.imgur.com/SkN50to.png"
						}
					}
				],
				"entries": []
			}
		},
		{
			"name": "Spell Scroll of Protection from Energy",
			"baseItem": "scroll|PHB",
			"type": "SC",
			"weaponCategory": "varies",
			"weight": 0,
			"armor": false,
			"ac": "0",
			"stealth": false,
			"rarity": "uncommon",
			"wondrous": false,
			"reqAttune": false,
			"value": 1000,
			"weapon": false,
			"source": "StonemoonShop",
			"entries": [
				"A spell scroll containing the spell {@spell Protection from Energy}.",
